CREATE TABLE shopping_user(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	login VARCHAR(20) NOT NULL,
	password VARCHAR(8) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uc_login UNIQUE (login)
);

CREATE TABLE shopping_list(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	shopping_user_id INT NOT NULL,
	item VARCHAR(100) NOT NULL,
	status INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (shopping_user_id) REFERENCES shopping_user(id)
);


